<?php
/**
 * Created by PhpStorm.
 * User: crlt_
 * Date: 2018/5/22
 * Time: 下午3:25
 */

namespace common\models;


use Yii;
use yii\base\Model;

class AdminLoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;


    private $user_;

    public function rules()
    {
        //   return parent::rules(); // TODO: Change the autogenerated stub

        return [
            [['username', 'password'], 'required'],
            ['rememberMe', 'boolean'],

            //password is validated by validatePassword
            ['password', 'validatePassword'],
        ];
    }


    /**
     * @return array
     */
    public function attributeLabels()
    {
        //  return parent::attributeLabels(); // TODO: Change the autogenerated stub

        return [
            'username' => '用户名',
            'password' => '密码',
            'rememberMe' => '记住密码',
        ];
    }

    /**
     * @return bool
     */
    public function login()
    {

        if ($this->validate()) {
            return Yii::$app->user->login($this->getAdminUser(), $this->rememberMe ? 3600 * 24 * 30 : 0);

        } else {
            return false;
        }


    }

    /**
     * @param $attribute
     * @param $params
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $adminuser = $this->getAdminUser();
            if (!$adminuser || !$adminuser->validatePassword($this->password)) {
                $this->addError($attribute, '用户名或密码错误！');
            }
        }
    }


    /**
     * @return null|static
     */
    protected function getAdminUser()
    {
        if ($this->user_ === null) {
            $this->user_ = Adminuser::findByUsername($this->username);
        }
        return $this->user_;
    }
}